#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")"

mkdir -p ./gramps
wget -qO- https://github.com/gramps-project/gramps/archive/refs/tags/v5.2.4.tar.gz | tar xvz --strip-components=1 -C ./gramps
cp ./gramps/example/gramps/example.gramps ./gramps/example/gramps/example.xml
sed -i "s#{GRAMPS_RESOURCES}#$(pwd)/gramps#g" ./gramps/example/gramps/example.xml
